name: 汽水音乐
desc: 过滤汽水音乐广告（Stash 专用）
icon: https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

mitm:
  hosts:
    - "*.douyin.com"
    - "*.qishui.com"
    - "*.zijieapi.com"

rewrite:
  # === 广告策略下发（核心）===
  - name: 汽水音乐-广告配置下发
    match: ^https:\/\/tnc\d+-.*\.zijieapi\.com\/get_domains\/v\d\/\?
    type: response-jq
    require-body: true
    argument: |
      del(
        .data.opaque_data_enabled,
        .data.ttnet_http_dns_enabled,
        .data.ttnet_quic_enabled,
        .data.ttnet_tt_http_dns,
        .data.splash_ad,
        .data.feed_ad,
        .data.popup_ad,
        .data.banner,
        .data.ads
      )

  # === 我的页面广告 ===
  - name: 汽水音乐-我的页面
    match: ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.com\/luna\/me\?
    type: response-jq
    require-body: true
    argument: |
      del(.reward_ad_banner)

  # === 卡片引导 ===
  - name: 汽水音乐-卡片广告
    match: ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.com\/luna\/card\?
    type: response-jq
    require-body: true
    argument: |
      del(.preview_guide)

script:
  - match: ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/me\/recently-played-media\?
    name: 汽水音乐-移除播放页视频流
    type: response
    require-body: true
    timeout: 30
    argument: SodaMusic_remove_ads.js

script-providers:
  SodaMusic_remove_ads.js:
    url: https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js
    interval: 86400