name: 汽水音乐-测试
desc: Stash Script 测试

mitm:
  hosts:
    - "*.douyin.com"
    - "*.qishui.com"

script:
  - match: ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/me\/recently-played-media\?
    name: SodaMusic_remove_ads
    type: response
    require-body: true

script-providers:
  SodaMusic_remove_ads:
    url: https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js
    interval: 86400
